### ISSUE TITLE
Enchanting Table Blank

### ISSUE THREAD

**Issue by crest1993** [Devan-Kerman/Stacc#1]
There is no crash log whatsoever, but you can't enchant equipment in Enchanting Table. Its just blanks after you put any equipment

![image](https://user-images.githubusercontent.com/20949355/85493167-9ab48b00-b600-11ea-9838-2ac78955c182.png)

the level 1,2,3 part is Blank
this screenshot is after I remove the mod temporarily.

**Comment by Ueaj-Kerman** [comment]
Hm

**Comment by Ueaj-Kerman** [comment]
ah, found it

**Comment by Ueaj-Kerman** [comment]
https://www.curseforge.com/minecraft/mc-mods/stacc/files/3012220

**Comment by Ueaj-Kerman** [comment]
wait no

**Comment by Ueaj-Kerman** [comment]
https://www.curseforge.com/minecraft/mc-mods/stacc/files/3012231 ok now fixed
