### ISSUE TITLE
/clear command only removes 2^32-1 items max at a time

### ISSUE THREAD

**Issue by James103** [Devan-Kerman/Stacc#10]
Stacc 1.16.1 5
Minecraft 1.16.1

When you use the /clear command, it only removes the first 4,294,967,295 items it comes across in your inventory. To reproduce:
1. `/give @p stone 1000000000` (x5)
2. `/clear`
3. Notice a stack of ~705M stone is left in your inventory.
4. Notice the result - "Removed 4,294,967,295 items from ..." instead of "Removed 5,000,000,000 items from ..."

**Comment by Ueaj-Kerman** [comment]
hmmm, that's the unsigned int max, not the signed one, how the hell

**Comment by Ueaj-Kerman** [comment]
I think this one is outside my control, maybe

**Comment by Nathan22211** [comment]
yeah I think the int max is baked into either the game or Java 8, you might have to change it to do the long max which is 2^64

**Comment by James103** [comment]
Closing, as this is a vanilla issue (even though it is only reproducible with mods).
