### ISSUE TITLE
You can fully repair a billion almost-broken diamond helmets with only 5 diamonds

### ISSUE THREAD

**Issue by James103** [Devan-Kerman/Stacc#11]
Stacc 1.16.1 5
Minecraft 1.16.1
See #5

In an anvil, you can fully repair a billion diamond helmets, each with 1 durability left, at a cost of just 5 diamonds and 5 XP levels. To reproduce:
1. `/give @p minecraft:diamond_helmet{Damage:362} 1000000000`
2. `/give @p diamond 999`
3. `/give @p anvil`
4. Place down the anvil.
5. Open the anvil interface.
6. Place the 1 billion diamond helmets in the "target" slot as a single stack, and place 5 diamonds in the "sacrifice" slot.
7. Look at the result. Expected: No change / rejected (the total durability on the diamond helmets is 363 billion, but a diamond only repairs 90, or an average of 0.00000009 durability across all diamond helmets). Actual: All 1 billion diamond helmets are fully repaired.

Additional steps to reproduce:
1. `/give @p minecraft:diamond_helmet{Damage:362} 100`
2. `/give @p diamond 100`
3. `/give @p anvil`
4. Place down the anvil.
5. Open the anvil interface.
6. Place the 100 diamond helmets in the "target" slot as a single stack, and place the 100 diamonds in the "sacrifice" slot.
7. Look at the result. Expected: Diamond helmets repaired to 25% durability, all diamonds are consumed. Actual: Diamond helmets fully repaired, leaving 95 diamonds in the "sacrifice" slot.
8. Repeat until step 6, but give yourself 150 diamonds instead.
9. Look at the result. Expected: Diamond helmets repaired to 37.5% durability, all diamonds are consumed. Actual: Diamond helmets fully repaired, leaving 145 diamonds in the "sacrifice" slot.

In both cases, the XP cost to repair is 5 XP levels.

**Comment by Ueaj-Kerman** [comment]
fixed, will be in next release
