### ISSUE TITLE
Signing a stack of books and quills consumes all but one of the books and quills.

### ISSUE THREAD

**Issue by James103** [Devan-Kerman/Stacc#12]
Stacc 1.16.1 5
Minecraft 1.16.1

When you sign a stack of (example) 1,234 books and quills all at once, it consumes 1,233 of the books and quills and leaves you with only 1 written book. Expected result: You should have gotten 1,234 of the same written book. To reproduce:
1. `/give @p writable_book 1234`
2. Write something in the book.
3. Sign the book.
4. Notice that all but one of the books and quills got consumed and that you only have 1 written book.

**Comment by Ueaj-Kerman** [comment]
fixed in next release
