### ISSUE TITLE
Anvil will not allow renaming items

### ISSUE THREAD

**Issue by James103** [Devan-Kerman/Stacc#13]
Stacc 1.16.1 6
Minecraft 1.15.2

When you attempt to rename any item (without repairing or enchanting it) at any stack size in any anvil (in Survival or Creative mode), the operation is rejected. The only way to rename an item is to repair or enchant it. In Stacc 1.16.1 5, renaming was still possible for any item. Most likely caused by the XP cost fix in #5.

**Comment by ghost** [comment]
I can confirm that this issue is present. It doesn't matter what Stack size you have configured you simply can't rename items unless you repair or enchant them (like James103 mentioned). The current Github repo isn't up to date so checking what the issue is is impossible.

**Comment by Ueaj-Kerman** [comment]
hm

**Comment by Ueaj-Kerman** [comment]
was this fixed, I think it is, imagine testing your own mod hahayes

**Comment by OmegaDerp** [comment]
I'm not sure, I had to remove this mod eventually because it conflicted with some mods (can't remember which ones).

**Comment by ghost** [comment]
I'm not sure, I had to remove this mod eventually because it conflicted with some mods (can't remember which ones).

**Comment by Ueaj-Kerman** [comment]
yep fixed
