### ISSUE TITLE
Suggestion: Prevent Durability Items from Stacking

### ISSUE THREAD

**Issue by T0paz** [Devan-Kerman/Stacc#14]
As it is right now, items that have durability and are stacked will lose durability when used (the durability loss is applied to all items in the stack). Instead of having to manually override every item with durability with a chance of missing one, a toggle which adapts to durable items, even ones added by mods, would be cool.

**Comment by James103** [comment]
#1, #5, and #11 (and possibly others) are related to the fact that items with durability can stack with this mod active.

**Comment by Ueaj-Kerman** [comment]
fixed, there is now an option `enable_stackable`, when set to false all non-stackable items become non-stackable
