### ISSUE TITLE
Suggestion: Be able to customize using mod menu or non-datapack config file

### ISSUE THREAD

**Issue by Jarfeh** [Devan-Kerman/Stacc#15]
Would it be possible for this mod to be customizable without having to use datapacks? I've only been able to get the mod working half of the time, as the game keeps ignoring the stacc folder in my datapack
Edit: I am trying to get this working on a server

**Comment by Ueaj-Kerman** [comment]
hmm good idea

**Comment by Ueaj-Kerman** [comment]
mod is now deprecated
