### ISSUE TITLE
Stacc API doesn't allow items to stack over 64 in player inventory 

### ISSUE THREAD

**Issue by Nathan22211** [Devan-Kerman/Stacc#16]
dunno if that's intentional or not, but clearly an oversight of a mod maker wants to use it and have it work in player invitories

**Comment by Ueaj-Kerman** [comment]
what do you mean, it should work just fine, seems to work for me. The mod must be present on the client and server btw

**Comment by Nathan22211** [comment]
I mean the API you use in a dev environment, this API `include "net.devtech:Stacc:1.0.0"`

**Comment by Ueaj-Kerman** [comment]
kinda late, but u need to keep it present at runtime too `modRuntime(include("net.devtech:Stacc:1.0.0"))`
