### ISSUE TITLE
Datapack not loading

### ISSUE THREAD

**Issue by Desempregago** [Devan-Kerman/Stacc#17]
![image](https://user-images.githubusercontent.com/14002834/104834496-8971eb00-587e-11eb-8188-9382c6f322cb.png)
it doesn't matter if I put the folder inside the datapacks folder inside the world folder or use Data Loader (global datapack mod)

**Comment by Desempregago** [comment]
Using stacc 1.0

**Comment by Ueaj-Kerman** [comment]
uhhh where are you putting the file

**Comment by Desempregago** [comment]
> "it doesn't matter if I put the folder inside the datapacks folder inside the world folder or use Data Loader (global datapack mod)"

**Comment by Ueaj-Kerman** [comment]
No I mean where are you putting stacc.properties

**Comment by Desempregago** [comment]
As I'm using Data Loader, I'm putting the file under `config/datapacks/stacc/stacc.properties`

**Comment by Desempregago** [comment]
Fixed by using KubeJS's data function (works better than DataLoader)
