### ISSUE TITLE
1.16.1 port

### ISSUE THREAD

**Issue by James103** [Devan-Kerman/Stacc#2]
Does this mod work on 1.16.1? If not, are you willing to port this mod to 1.16.1? Latest version says it's for 1.15.2.

**Comment by Ueaj-Kerman** [comment]
I don't see why it shouldn't

**Comment by Ueaj-Kerman** [comment]
fixed, turns out it didn't work https://www.curseforge.com/minecraft/mc-mods/stacc/files/3012196
