### ISSUE TITLE
Crash on launch - 1.16.1 Fabric 0.9.0.204

### ISSUE THREAD

**Issue by shikyo13** [Devan-Kerman/Stacc#3]
Crash on both client and server when trying to startup with this mod

**Comment by Ueaj-Kerman** [comment]
Logs pls

**Comment by shikyo13** [comment]
Here is the latest.log from client. No crash report is generated as the console doesn't even open with this mod included. Same results both server and client.

https://pastebin.com/RBpXdg5t

**Comment by shikyo13** [comment]
Nevermind, was able to get it generate a crash report this time https://pastebin.com/Bq8hxSgi

**Comment by Ueaj-Kerman** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/stacc/files/3012196
