### ISSUE TITLE
Success message in /clear has negative numbers

### ISSUE THREAD

**Issue by James103** [Devan-Kerman/Stacc#4]
Minecraft 1.16.1
Stacc 1.16.1 4

When the number of items cleared is at least 2147483648 (modulo 4294967296), the value displayed for the number of items cleared when using the `/clear` command is negative. To reproduce, run a `/give @p stone 1000000000` command 3 times, then run `/clear`.

**Comment by Ueaj-Kerman** [comment]
hmmm, I don't see a clean way of implementing this

**Comment by Ueaj-Kerman** [comment]
nvm I found a good enough:tm: way to do this, will be in the next release
