### ISSUE TITLE
Breaking furnaces, chests, and similar containers with maxed-out stacks freezes and crashes the game.

### ISSUE THREAD

**Issue by James103** [Devan-Kerman/Stacc#7]
Minecraft 1.16.1
Stacc 1.16.1 4

When you put a maxed-out stack (1,000,000,000) of any item in a single container, and then break that container, the game will freeze (and eventually crash with java.lang.OutOfMemoryError) due to millions of item entities being spawned in at once. Despite the increased max stack size, the game still limits item entities to containing a stack of 64 items each.

**Comment by Ueaj-Kerman** [comment]
concern, ok will look into it

**Comment by Ueaj-Kerman** [comment]
aye mojang did a stupid, fixed in next release
