### ISSUE TITLE
[Suggestion] Make a minimum stack size, so non-stackable items doesn't stack (can be overrided)

### ISSUE THREAD

**Issue by Desempregago** [Devan-Kerman/Stacc#8]
For THIS to not happen
![unknown](https://user-images.githubusercontent.com/14002834/88404024-b64bb680-cda3-11ea-9209-de00386ba8d6.png)

**Comment by Ueaj-Kerman** [comment]
You can already set the stack size for individual items, though more advance selection would prolly be a good idea

**Comment by Nathan22211** [comment]
yeah you might want to add the ability to use item tags

**Comment by Ueaj-Kerman** [comment]
fixed, there is now an option `enable_stackable`, when set to false all non-stackable items become non-stackable

though tag support and stuff will have to come at some point, can u make a new issue for that?

**Comment by Desempregago** [comment]
Sorry for commenting on an already closed issue, but what I was referring to was **to set a minimum stack size to make ONLY already stackable items to stack correctly, like how StackUp (1.12) does:**
![image](https://user-images.githubusercontent.com/14002834/108146049-3d97a900-70ab-11eb-9342-a962f4cfb46c.png)
