### ISSUE TITLE
Item duplication with splitting very large stacks

### ISSUE THREAD

**Issue by James103** [Devan-Kerman/Stacc#9]
Stacc 1.16.1 5
Minecraft 1.16.1

When you give yourself a billion of an item and split the resulting stack into 3 equal-sized portions, then recombine, you are left with 32 extra items. This process can be repeated over and over again, netting you 32 additional items each time. This is most likely because 32-bit floating point numbers are used somewhere in the item splitting functions.

**Comment by Ueaj-Kerman** [comment]
what in the world :concern:

**Comment by Ueaj-Kerman** [comment]
you're exactly right, nice!
![image](https://user-images.githubusercontent.com/28693059/89107366-3ef6d200-d3f6-11ea-99df-e8b8f4231a59.png)

**Comment by Ueaj-Kerman** [comment]
fixed, will be in next release
